add Periodic Batching config options
saguiitay/serilog-sinks-azuredataexplorer pull request #37
Opened 2024-08-13 14:25 UTC by monishkadas-ms

Updated the logger configuration to accept Periodic Batching Configuration parameters from appsettings.json

2024-08-13 14:48 UTC, tanmaya-panda1 commented
@monishkadas-ms Please do update the docs as well

2024-08-14 05:44 UTC, ag-ramachandran commented on README.md
>  ```
Library versions have to be bumped up

2024-08-14 05:45 UTC, ag-ramachandran requested changes
Bump up versions

2024-08-14 05:59 UTC, monishkadas-ms commented on README.md
>  ```
Done!

2024-08-14 06:01 UTC, ag-ramachandran approved these changes

2024-08-14 07:03 UTC, tanmaya-panda1 approved these changes

2024-08-14 08:21 UTC, merged