add test for appsettings.json based config
saguiitay/serilog-sinks-azuredataexplorer pull request #38
Opened 2024-08-22 10:50 UTC by monishkadas-ms

Updated the AzureDataExplorerSinkE2ETests.cs with a test for checking sink configuration using appsettings.json.

Updated LoggerConfiguration to accept userToken as a parameter from appsettings.json to allow userToken based Authentication Method.

Added additional packages and updated Serilog version

2024-08-26 16:46 UTC, tanmaya-panda1 requested changes

2024-08-26 16:46 UTC, tanmaya-panda1 commented on src/Serilog.Sinks.AzureDataExplorer.Tests/AzureDataExplorerSinkE2ETests.cs
> +
adding this AppSettingsConfiguration as a part of existing test cases is not a good idea. Please do create separate method to test this config.

2024-09-02 04:28 UTC, monishkadas-ms commented on src/Serilog.Sinks.AzureDataExplorer.Tests/AzureDataExplorerSinkE2ETests.cs
> +
Done!

2024-12-09 01:48 UTC, ag-ramachandran approved these changes

2024-12-12 04:39 UTC, tanmaya-panda1 approved these changes

2024-12-12 05:30 UTC, merged